### ISSUE TITLE
Consider reorganizing config file parameters in config creator GUI

### ISSUE THREAD

**Issue by HEdingfield** [BrightSpots/rcv#123]
[This comment](https://github.com/BrightSpots/rcv/issues/45#issuecomment-404650567) provides an example of a flow that might be more user-friendly.

**Comment by gngilbert** [comment]
Looks like a good subject for future enhancements.

**Comment by HEdingfield** [comment]
Interesting looking back on that questionnaire idea now. @chughes297 and any others who want to chime in: do we reckon the GUI revamp effectively accomplishes what was in the spirit of [that original comment](https://github.com/BrightSpots/rcv/issues/45#issuecomment-404650567)? Or is there more we can take from that now to include in the revamp?

**Comment by chughes297** [comment]
I think in general we have handled this suggestion's proposals, but a few things come to mind looking through it: 

- Number of Rankings for this contest seems like a better way to phrase the "how many candidates can you rank" prompt

- Intrigued by including this question: "Is there a Write-In Position" because the tabulator assumes write-ins, to some extent. not sure where to go with this, though

- Assumes the tabulator could run multiple contests at once, in which case we would need to add a question about how many RCV contests you want to tabulate, right?

**Comment by HEdingfield** [comment]
Per email conversations today:

* Going with "Maximum Number of Candidates That Can Be Ranked"
* Seems like there are outstanding questions on this; please file a separate issue if anyone is interested in investigating further.
* Seems like there are outstanding questions on this; please file a separate issue if anyone is interested in investigating further.
