### ISSUE TITLE
figure out the path forward with Whitney's visualizer

### ISSUE THREAD

**Issue by tarheel** [BrightSpots/rcv#148]

**Comment by CalebKleppner** [comment]
Gents:  Whitney shared her login to Word Press, where all of their visualizer code is stored with the understanding that we would only use the info to download the code but not make any changes on the site.  Code is in php.  Here is the login information:

http://election-results.civicdesign.org/wp-login.php
User:	RCVRC
Pw:		N8CMMqzFv(%BTA%BcgpX%a6)

**Comment by CalebKleppner** [comment]
Oops, didn't mean to close the issue.  Whitney told us a few things that are worth passing on:

First, when she used the visualizer for recently-created summary files, the system failed to read much of the data from the file.  She thought it might be a data-type problem, but even when she stored Excel data as numbers instead of text, the visualizer still failed.  She suggested looking at the files functions-bkp.php and PHPExcel.php, which is where she suspects the data-reading error is happening.
