### ISSUE TITLE
finalize and implement new output format(s)

### ISSUE THREAD

**Issue by tarheel** [BrightSpots/rcv#181]
We need output that's both human-readable (like our current XLSX) and suitable as an input to the visualizer.

My recommendation is to have two separate outputs; I worry that otherwise we'll be continually making compromises between the two use cases, which are quite different.

If we do it this way, the tabular output can remain similar to what we have now (but switch from XLSX to CSV/ODS), and the visualizer output can be whatever we think is the most extensible (I would lean toward JSON, personally).

An alternative would be to start with a single CSV format unless/until we see a strong need for separate outputs.

**Comment by moldover** [comment]
I played around with some csv fomats and reached the same conclusion: no clean way to support both batch elimination and provide vote redistribution info to support the sankey visualization in CSV.  @CalebKleppner says we can forego batch elim for the visualizer, which is good, but I think there's a case for unit testing wanting to know about batch elim (maybe other odds and ends too) which leans me towards splitting the outputs as Louis suggests for the flexibility. 

If we go this route there is no immediate need to switch the current summary, but it probably makes sense as part of a cleanup pass for test lab submission.  I can take that on since I look forward to tearing some of it out ;)

Better precinct reports #105 would no longer be possible.  There do seem to be some [scripty](https://stackoverflow.com/questions/12162477/importing-multiple-csv-to-multiple-worksheet-in-a-single-workbook) ways to make that happen from within Excel, which maybe is good enough.

**Comment by moldover** [comment]
@tarheel @HEdingfield I changed over the existing output to csv and am moving on to the json output + transfer counts for the sankey plot.  To refresh, I'm thinking of the "transfer counts" as a list (or multiple lists if there were multiple winners or losers in a given round) which shows how many votes transferred from each winning/losing candidate to other candidates, for that round.  Something like:
round 1: 
  loser 1:
     transfer to candidate a: 10
     exhausted: 10
  loser 2:
    transfer to candidate a: 5
    transfer to candidate b: 1
    ...
....  

I think the way to do this is just build and update this structure during the main tabulate loop: whenever a vote is transferred we currently update the cvr to reflect this.  I will add calls to update this structure at those same points.  Not exactly elegant, but doesn't seem too complicated either. 

Note: I can imagine also doing all this after tabulation is complete, by looking through cvrs, but that seems more costly, and I would need to add round information to the cvrs to make that possible.

**Comment by tarheel** [comment]
Yeah, you could keep running totals by updating a map from roundNumber to fromCandidate to toCandidate to tally: a `Map<Integer, Map<String, Map<String, Integer>>>`.

**Comment by moldover** [comment]
Yep, that's what I have.  Thanks.

**Comment by moldover** [comment]
I'm closing this as the new formats have been "implemented".  There will undoubtedly be revisions to them, but those can be new issues, more specific to the task at hand.
