### ISSUE TITLE
enable editing of candidates and CVR source files in GUI

### ISSUE THREAD

**Issue by tarheel** [BrightSpots/rcv#207]
Currently this isn't possible. If you want to edit an item, you have to remove it and re-add it.

**Comment by HEdingfield** [comment]
No out-of-the-box support for this with the `TableView` class unfortunately, but there are a [couple](https://www.youtube.com/watch?v=_FBPukQOLCY) of [videos](https://www.youtube.com/watch?v=z4LVoLg6ch0) that demo this.

**Comment by gngilbert** [comment]
While it would be very useful to me in testing, I agree that it is not critical at this point.  However, at the point where independent users are using it regularly, it would make a big difference to some of them.  We can put it on hold for now if it is problematic but let's not forget it.  thanks.

**Comment by CalebKleppner** [comment]
UI that changes would be nice at some point:  a) an edit button on the candidates tab so that you can change the spelling of a name, add or change a code and switch a candidate to or from excluded.  Generally, we just enter a candidate name and then click “Add”, so the add button should be immediately to the right of Name * (and one tab away).  Then we should have the box for Code, the check box for “Excluded”, then “Edit Selected” and finally “Delete Selected”. So the final order would be:

     Name *, Add, Code, Excluded, Edit Selected, Delete Selected

b) Any way to re-order candidates?  Drag-n-drop would be nice ...

![image](https://user-images.githubusercontent.com/41450076/51409682-8e392280-1b30-11e9-94d2-107cdf5b2e7f.png)

c) On the CVR Files tab, is it worth adding an Edit button and possibly a method of reordering CVR files?

![image](https://user-images.githubusercontent.com/41450076/51409701-97c28a80-1b30-11e9-818d-a2d330e553f2.png)

**Comment by gngilbert** [comment]
All sounds good to me.

George Gilbert
RCV Resource Center
george.gilbert@rankedchoicevoting.org
336-906-0047

**Comment by gngilbert** [comment]
We have been approached by ES&S regarding their interest in partnering with us to offer several Utah jurisdictions a combination of ES&S voting system and the UTab Software to conduct RCV elections this spring.  As I understand it, both Utah jurisdictions with spring elections include multi-winner offices that will likely employ the "sequential tabulation" process.  It would definitely be best if we could offer this capability with the ability to edit a candidate's "excluded" status.  

I will be discussing this prospect in greater detail with ES&S's Utah rep. and Paige will be discussing with Steve Pearson (also ES&S) the prospect of including the UTab Software in one of their pending certification submissions.

How difficult would it be to make this enhancement?

**Comment by tarheel** [comment]
That's exciting! @HEdingfield is the best person to comment on the difficulty.

**Comment by gngilbert** [comment]
I figured Hylton would be the one.  Lots of exciting prospects out there
right now.
BTW, I sent you the CVR file.  Sorry about the mix up last night.

George Gilbert
RCV Resource Center
george.gilbert@rankedchoicevoting.org
336-906-0047

**Comment by HEdingfield** [comment]
I could probably get editing existing entries for candidates and CVRs done next week. We wouldn't need an "edit selected" button, because I could probably make it so you just double click on the entry in the table you want to edit to change it.

@CalebKleppner you can already sort by any field you want by just clicking the column header at the top. Did you need something more than this?
