### ISSUE TITLE
validate CDF source files

### ISSUE THREAD

**Issue by tarheel** [BrightSpots/rcv#309]
There are various checks we can run when we parse CDF files to make sure everything is internally consistent, e.g. there aren't any votes for candidates that aren't in the list of valid candidates. Hopefully we can reuse code from John Dziurlaj instead of writing our own.

**Comment by artoonie** [comment]
Any additional tips to make this more concrete? I'm not familiar with the list of issues that may go wrong, or with where I might find John Dziurlaj's validations.

**Comment by artoonie** [comment]
Analysis of basic things that seem likely to go wrong:
1. Invalid Contest Selection is already handled: `ContestSelection "ics-b" from CVR not found!`
2. Invalid Candidate name is not handled: `Cannot invoke "java.util.HashMap.get(Object)" because "candidate" is null`
3. Duplicate Candidate @id is not handled. Uses last-entered Candidate ID and overwrites any previous usage.
4. Duplicate Candidate @name is not handled. Maps all @ids using that @name to the same candidate.

I'll implement nicer errors for 2-4, plus a nicer generic error.

**Comment by artoonie** [comment]
@rrojas350 can you prioritize this task? https://github.com/BrightSpots/rcv/issues/645
