### ISSUE TITLE
ensure that batch elimination is compatible with continueUntilTwoCandidatesRemain

### ISSUE THREAD

**Issue by tarheel** [BrightSpots/rcv#396]
Recommendation from Chris Jerdonek and David Cary:

> We agreed that the way to modify the batch elimination rule so that it also works with reduce-to-two is simply to exclude from consideration batches that would eliminate all but one candidate. So one way to state the rule would be as follows:
> 
> Define a "batch" of candidates in a round to be all of the candidates whose vote totals are less than some candidate (you can call this the "next" candidate). Then to do a batch elimination, eliminate the largest batch that satisfies both of the following conditions (1) the sum of the vote totals of the candidates in the batch is strictly less than the vote total of the next candidate, and (2) at least two candidates aren't in the batch.

**Comment by cjerdonek** [comment]
Thanks, @tarheel!

Also, below is an example to help others understand how to apply the rule and where it can make a difference. Consider these 7 candidate vote totals that sum to 100:

1. 60
2. 15
3. 14
4. 5
5. 4
6. 1
7. 1

Observe in this case that the top candidate has a majority (60 out of 100). There are three batches of candidates that satisfy condition (1) from the original comment: the bottom two (1 + 1 = 2 < 4), the bottom four (1 + 1 + 4 + 5 = 11 < 14), and the bottom six (40 < 60).

And there are two batches that satisfy condition (1) and (2): the bottom two and the bottom four. Since the second batch is the largest of these, you would eliminate the bottom four in this round, leaving three candidates in the next round. (Also, observe that you wouldn't want to eliminate the bottom five candidates because intermediate eliminations could cause a change in the second place candidate.)

**Comment by HEdingfield** [comment]
Cool caveat, and thanks for sharing the example, @cjerdonek! It's now one of our automated tests.
