### ISSUE TITLE
Add “CSV” as “provider”

### ISSUE THREAD

**Issue by andyanderson** [BrightSpots/rcv#549]
Very generally, cast vote records from non-standard sources may come in as CSV with one of the following two formats:

| VoterID | Rank1 | Rank2 | Rank3 |
| ------- | ------ | ------ | ------ |
| AD2F7 | Cyd | Ann | Bob |
| … | … | … | … |

or 

| VoterID | Ann | Bob | Cyd |
| ------- | ------ | ------ | ------ |
| AD2F7 | 2 | 3 | 1 |
| … | … | … | … |

The former is similar to Hart, but currently one has to experiment to figure this out because all one knows is that it’s CSV and it’s not from one of these providers.

The latter, in particular, comes out of Qualtrics, but doesn’t seem to correspond to any of the current options.

It would be nice if the program would provide a generic “CSV” provider, with a toggle that would switch between these two formats.

Thanks!

**Comment by tarheel** [comment]
Good suggestions!

Btw, the former is identical to the ES&S format except that the tabulator expects an Excel file, not a CSV.

Anyway, we haven't bothered to add this yet because no one has specifically requested it, but it wouldn't be a difficult change. If you think you (and/or others?) would use it, I can try to include it in the next release.

**Comment by andyanderson** [comment]
Appreciate it! It’s definitely of interest, I think in general. We’re doing student government elections here in April, for the first time with RCV, and Qualtrics provides a secure and private platform with a good ranking option. I know that other student governments across the country are also using Qualtrics for their elections, and it would be nice to point them toward the tabulator as a way to encourage them to use RCV. 

This is also the format of data produced by Google forms, so it would be a way to really generate some widespread usage: https://forms.gle/hkzFNr2YabBjNMVn8

**Comment by mikejcorey** [comment]
As a data journalist who trades in government data files all the time, I'd chime in and say allowing CSV as a file type would be useful. Minneapolis releases its RCV CVRs as CSVs, and CSVs are a more accessible format than XLSX. It's not that hard to convert it back to an XLSX, but if it's an easy change it would be a good one.

**Comment by greg-dennis** [comment]
I want to be sure that the thrust of @andyanderson's original request isn't missed here. Accepting CSVs is one thing, but for me, the more important request is support for the "latter format," where the columns are the candidate names and the cells contain the ranking number. That's the real win here, because that's the format outputted by all these standard college and university systems and by Google Forms. Enabling people to host a (free) Google form to collect the data and then use the (free) Tabulator would be significant.

Whether CSV is supported, I think, is somewhat secondary, because someone can convert a CSV to XLSX if needed. But what is much harder is the conversion from the column=candidate to column=rank format. It might make things clearer to split this issue into two: one to support CSVs and the other to support column=candidate.

**Comment by andyanderson** [comment]
Hi, everyone,

I wrote a python script that converts qualtrics files to ES&S format so that the former can be used for elections:

https://github.com/AmherstCollege/qualtrics2ess

I meant to get this out much sooner, but was distracted by many other tasks. It’s actually a little more general, in that it also creates a CDF file that includes all candidate names, including write-ins, which are otherwise an onerous task to add.

If you were willing to promote it as an option for the tabulator that would be great. You might also find the code useful as a starting point for your own implementation.

— Andy

**Comment by HEdingfield** [comment]
I'm personally just stoked to see that the tabulator is finally being used to determine which vegetable is best.

Nice script! Maybe we can port some of this logic over in our next sprint.

**Comment by andyanderson** [comment]
Yes, this was a demonstration of RCV for the Amherst College student government, so food is always a popular topic. Unfortunately not a large voter pool, I may update that later.

I also wrote a manual for setting up an election with Qualtrics, converting it with this script, and running it through the RCV Tabulator and RCVis:

https://docs.google.com/document/d/1MT7JORmGbe4ALw4sfMT8w2_Wgs_8MJcbUVcXUcMc5BA/edit#

**Comment by artoonie** [comment]
There are a few nuances here that I'm not sure we want to handle natively:
1. In the qualtrics CSV, there are a lot of "magic numbers" -- the eleventh column is where the candidate names begin; the first row contains IDs for each candidate; the second row contains their names; the third row is ignored.
2. In the google sheets CSV, candidate names are surrounded by brackets `[]` and the first row is a to-be-ignored timestamp.

Since our goal is to have a generic, simple reader, I think it makes sense to assume a clean input, like the tables in the initial issue description, rather than handling all special cases.

Then, rather than building many separate CSV parsers, we can have a simple converter (like qualtrics2ess) that takes various CSV formats and creates a standard format from them -- just because there can be a huge number of possible CSV formats here, and making each one a Reader may be overkill.

![Image](https://user-images.githubusercontent.com/537316/229577111-a6db574b-0567-4832-ab1e-12b45eb4e6ee.png)

Thoughts on just creating the Generic CSV Reader as part of this ticket, and evaluating later whether it's worthwhile to build the Qualtrics/GoogleForm-specific readers?

**Comment by greg-dennis** [comment]
I am fine with a generic CSV reader without specializing it to Qualtrics or Google Forms. It's not unreasonable to expect users to do some modest cleanup / standardization of their CSV's in advance and, as you stated, more specific converters are always possible to add in the future.

However, I wouldn't conflate "candidates in header / ranks in cells" and CSV format if we don't have to. Can they just both be orthogonal toggles? That is, someone can toggle between (candidates in headers / ranks in cells) and (ranks in headers / candidates in cells); and _separately_ toggle between CSV and Excel (doesn't have to be a toggle per se, could be inferred from the file extension)? It seems like all combinations should be generically possible without too much work?

**Comment by artoonie** [comment]
I'm a little afraid to make things prematurely generic, since the primary use case (supporting files from vendors) wont have this transposition. Glancing at the code, it's not super trivial. It would be if the code were just a 2D loop (we could swap the order of the loops), but the readers are often class-based. I haven't looked super deeply, but I'll let others make the call here.

Rather than add complications to the Readers, I have a preference for a Preprocessing option: something that takes CVRs and can do a variety of tasks. For example:
1. Make all candidates Title Case
2. Transpose CVRs (swap rows/columns)
3. Convert Specific CSVs to Generic CSV
This has a few benefits, including (1) validating that the preprocessing worked as expected, and (2) keeping the "golden path" clean, straightforward, and easier-to-validate.

**Comment by HEdingfield** [comment]
I might be wrong, but I don't believe #649 handled transposing CVRs / adding an orthogonal toggle (i.e. Qualtrics format).

**Comment by artoonie** [comment]
Agreed -- the automation closed this, but qualtrics is not yet supported. I believe that the priority has decreased though, as the Qualtrics format is a nice-to-have (per the comment thread), not a requirement.

**Comment by HEdingfield** [comment]
In that case, I think it's totally worth splitting that off into a separate issue with a lower priority tag and just linking back to this one for reference. Spun out #671 for this.
