### ISSUE TITLE
Ability to Edit Info in Tables

### ISSUE THREAD

**Issue by rrojas350** [BrightSpots/rcv#590]
Users would like the ability to edit tables in CVR files and Candidates, making it easier to edit the info if necessary. This could be achieved by adding a clickable icon to the table/row, such as a pencil, to edit the contents in the table and then save their changes by clicking the icon again.

**Comment by rrojas350** [comment]
Related to #502

**Comment by tarheel** [comment]
@HEdingfield: what do you think? I know we disabled editing in the past because of the confusing UX... but what about a pencil icon (as @rrojas350 suggested) that triggers an editing state for the row? And then, if you modify something in the row, we show Update/Cancel buttons. If there's no good way to fit this in the existing window, opening a separate modal would also be an option.

**Comment by HEdingfield** [comment]
Lowest effort would be to bring back what we had before, because I could probably piece it together by reversing the PRs that removed it. A modal would probably take 2 or 3 times as much effort, and would be tricky (as would the pencil thing), because we're working with a particular widget here that likely has limited APIs.

**Comment by tarheel** [comment]
The pencil approach seems worth investigating, since there's at least the possibility that it's not too bad. I'm inclined to agree that a modal probably isn't worth the trouble, so if the pencil is too difficult or impossible, restoring the old behavior seems OK.

**Comment by ggilber1** [comment]
Glad to see you guys considering restoration of the edit function.  As a former election official who created many election databases, the ability to edit an erroneous entry is always the first option looked for.

**Comment by HEdingfield** [comment]
Important discussion in [this thread](https://github.com/BrightSpots/rcv/pull/639/files#r1141150539) about how this design should work for the aliases field.

**Comment by chughes297** [comment]
Just commenting here to flag that Gretchen Reinmeyer in Arlington requested this feature as well. Seems high priority for the next release. 

May need a bit of context for this comment:

> Important discussion in [this thread](https://github.com/BrightSpots/rcv/pull/639/files#r1141150539) about how this design should work for the aliases field.

I read through and not seeing how this relates? May have missed some discussion. 


> @HEdingfield: what do you think? I know we disabled editing in the past because of the confusing UX... but what about a pencil icon (as @rrojas350 suggested) that triggers an editing state for the row? And then, if you modify something in the row, we show Update/Cancel buttons. If there's no good way to fit this in the existing window, opening a separate modal would also be an option.

I didn't realize this was removed for UX reasons. I don't remember the UX being all that confusing?

**Comment by HEdingfield** [comment]
> I read through and not seeing how this relates? May have missed some discussion.

It's just implementation details about how to separate multiple values for display in the table vs. the editing pop-up vs. how we store it in the backend.

> I didn't realize this was removed for UX reasons. I don't remember the UX being all that confusing?

#502 documents why it was confusing.
