### ISSUE TITLE
Alias for Candidates

### ISSUE THREAD

**Issue by rrojas350** [BrightSpots/rcv#591]
Ability to add an Alias for Candidates. Some CVRs may contain variations of a Candidate's name, as not all jurisdictions are given the freedom to adjudicate write-ins to match an existing candidate. Having aliases for candidates will help produce accurate results for these jurisdictions. 

Related to #60

**Comment by rrojas350** [comment]
Adding to this. When testing multi-vendor tabulation I ran into an issue where a candidate's name had a variation in one CVR and not the rest. Ideally, everything should be consistent when dealing with a multi-jurisdiction race but this feature could be used to resolve any potential candidate name variations.

**Comment by tarheel** [comment]
Makes sense. It might be a little tricky to figure out how to support this on the UI side, but the internal implementation shouldn't be too bad.

**Comment by chughes297** [comment]
Could we resolve this with #60 ?

**Comment by tarheel** [comment]
The original intention in #60 (gathering candidate names from CVR sources) would not be sufficient on its own. But we actually ended up discussing the alias idea in that issue also.

My preference would be to move forward just with alias support for now, since that's relatively straightforward and should provide a reasonable workaround to the problematic cases people have raised.

**Comment by ggilber1** [comment]
I am certainly in favor of separating the issues #60 and #591.  The original intent of #60 got seriously sidetracked by the normalization of write-ins discussion.  While the added complexity Rene has raised here, of name variations between CVRs supplied by different voting systems, certainly comingles the issues, I feel auto-populating candidate names is a priority that needs to finally be incorporated into RCTab for all vendors.

**Comment by artoonie** [comment]
Thoughts on just a big textbox asking for one name per line? I toyed with a couple options (e.g. "Add Alias" similar to the "Add Candidate") but that had a confusing UX.

Pros: easy, clear UI
Cons: more potential for error, e.g. user may comma-separate, tab-separate, or use both commas and newlines.

![Image](https://user-images.githubusercontent.com/537316/225206181-7c9a7fb1-5c58-41fe-bcc3-f57181b79f2d.png)

**Comment by artoonie** [comment]
Thinking on this more -- it seems that the notion of "Alias" supersede the notion of a "Code".

i.e. if instead of a Code, users entered a single Alias, wouldn't that be the same?

I'm still familiarizing myself with the source code, but this seems true on the surface. If it's true, I can handle them the same way internally, and we can have a discussion about whether the UI should keep them separated or not.

**Comment by rrojas350** [comment]
This is a tricky one. We need Code to stand alone because Hart and Dominion use candidate codes. I created a mock up with two options that could work as far as UI. 

![image](https://user-images.githubusercontent.com/98929622/225396786-7035e864-2bc2-4c49-bbcd-5296402f73f4.png)

Option 2 maybe easier because editing information in the table has been listed as a 1.4 requirement and the alias should appear there anyways, to inform the user.

**Comment by artoonie** [comment]
Is there a reason Hart/Dominion can't put the candidate code in the aliases box? Functionally, it will be the same, and it creates one fewer box in the UI which is nice. (Happy to hop on a call to discuss!)

Happy to use `;`-separation instead of newlines.

**Comment by artoonie** [comment]
See the Pull Request Comment for final implementation details:
#639
