### ISSUE TITLE
Consider gathering candidates from CVRs rather than specifying them in the config

### ISSUE THREAD

**Issue by HEdingfield** [BrightSpots/rcv#60]
Any compelling reasons not to do this?

**Comment by tarheel** [comment]
I'm not sure. Technically there's no problem, of course. I'd defer to Caleb and George on what's appropriate: a) require listing candidates (current approach), b) never list candidates in the config, or c) optionally list candidates.

**Comment by HEdingfield** [comment]
Yeah, would be good to get their opinion. Here's what I think makes the most sense:

1. User loads CVRs, and relevant data is scraped (candidates, precincts, etc.)
2. User is then brought to a screen where they can configure the tabulation and they're presented with options here that are specific to the behavior of the tabulator alone. They could also load an existing config file here.
3. User executes tabulation.

**Comment by CalebKleppner** [comment]
This would be a nice feature, but it's not needed for testing submission 1.0, so let's keep our focus on that.

**Comment by gngilbert** [comment]
We do this for CDF input files.  How much work would it be to do it for ESS inputs?

**Comment by tarheel** [comment]
The actual code wouldn't be very hard. The part I'm uncertain about is the user experience. How exactly would this work? I can think of at least a couple options. @HEdingfield's suggestion above sounds good, but would be a pain to implement in the UI. A couple alternatives:

1. On the candidates tab, there's a button labeled "Import from CVR sources" that triggers an immediate parsing of the source files, then overwrites the displayed list with whatever it finds. (In other words, the candidates still go in the config file, but we help the user auto-populate them.)
2. On the candidates tab, there's a checkbox to toggle whether the candidates are specified explicitly vs. inferred from the CVR sources. If the latter, the config doesn't contain candidate info, and the tabulator just assumes that any candidate it encounters while parsing the CVR sources is valid.

**Comment by gngilbert** [comment]
I like option 1.

**Comment by gngilbert** [comment]
One contingency we need to consider is a post-adjudication CVR where write-ins have been normalized.  Obviously there could be errors in the normalization process or records missed in the adjudication.  auto-populating the candidate names list would help catch these types of errors.

**Comment by andyanderson** [comment]
I just came to request the ability to “normalize” write-ins, and I see it mentioned here. My thought is that the Candidates tab should include a column to provide a standard alias for a given candidate that an election official can use to group different forms of a write-in, e.g. “B. Clinton”, “Bill Clinton”, “William J. Clinton”, etc. could all be grouped under “Bill Clinton” and then all collected together as that candidate for the tabulation.

I see that “Write-in reconciliation of aliases” is part of the specification in section 1.1.4-I of the “Voluntary Voting System Guidelines” here:

https://www.eac.gov/voting-equipment/voluntary-voting-system-guidelines

«Reconciliation of aliases means allowing election officials to declare two different spellings of a candidate's name to be equivalent (or not), as could happen from write-ins. Reconciliation of double votes means handling the case where, in an N-of-M contest, a voter has attempted to cast multiple votes for the same candidate using the write-in mechanism.»

Otherwise there is no choice but to go in and modify the ballots directly, which raises all kinds of red flags. 😲

Thanks,

— Andy

**Comment by tarheel** [comment]
I think the quickest (least amount of coding effort) way to enable support for an arbitrary number of aliases per candidate would be to add a single "Aliases" column on the Candidates tab and allow users to enter a comma-separated list in that field. But I acknowledge that that wouldn't be a great UX.

I can think of various ways to make it a cleaner interaction (e.g. something along the lines of what you proposed), but the design we actually build will probably depend a lot on what's feasible using the super-clunky JavaFX components.

**Comment by andyanderson** [comment]
Keep in mind that the software already requires a complete list of candidates, write-in or otherwise. The current form on the Candidates page asking for candidate name, code, and exclusion should be easy to extend with an additional “Alias” field, which I think will match how a user will enter this information by hand (discover write-in, determine most appropriate name, enter them together).

The CDF is also easily extended:

        {
            "name": "William J. Clinton",
            "code": "",
            "excluded": false,
            "alias": "",
        },
        {
            "name": "Bill Clinton",
            "code": "",
            "excluded": false,
            "alias": "William J. Clinton",
        },
        {
            "name": "B. Clinton",
            "code": "",
            "excluded": false,
            "alias": "William J. Clinton",
        },

The hardest part, I assume, is the code to transfer a vote for a write-in candidate to the alias candidate, when present. It does mean checking for the latter’s existence for every vote.

Transparent practice would also list the aliases together when describing / displaying the vote totals.

These are not always outlier events, every so often write-in candidates can garner substantial numbers of votes, and (rarely) even win. My current state senator won her first primary with 14,000 votes!

**Comment by tarheel** [comment]
If we don't have to keep track of each candidate's breakdown by alias during and after the tabulation, the non-UI changes should be pretty simple: just map each candidate to the normalized candidate name when parsing the CVRs, and then I guess add a column to the results CSV that includes all the aliases for each candidate.

**Comment by andyanderson** [comment]
Agreed.

**Comment by andyanderson** [comment]
Agreed it would be good to substitute aliases when parsing the CVR. But this becomes a two- (or more-) round process. I’m not clear at what point the CVR is parsed by the Tabulator — only when menuing **Tabulation** > **Validate** or **Tabulation** > **Tabulate**? (I know the latter always validates first.) In any case, assuming new code is added to the Tabulator to generate the contents of the Candidates tab, should this be a separate function or part of validation? I think it could be the latter. Then:

1. CVR is parsed and candidates compiled and listed in Candidates for review. If a CDF file has been loaded and it already contains aliases, those are substituted for write-ins. 
2. Election manager reviews write-ins and if necessary assigns aliases.
3. CDF file is saved, manually or when required before tabulation.
4. Repeat the above at least one more time to capture all aliases.

I think this would be the simplest approach.

**Comment by ggilber1** [comment]
I am certainly in favor of separating the issues #60 and #591.  The original intent of #60 got seriously sidetracked by the normalization of write-ins discussion.  While the added complexity Rene raised in #591, of name variations between CVRs supplied by different voting systems, certainly comingles the issues, I feel auto-populating candidate names is a priority that needs to finally be incorporated into RCTab for all vendors.

**Comment by ggilber1** [comment]
I would recommend moving this to a higher priority.??  @rrojas350 @chughes297

**Comment by artoonie** [comment]
My plan is to follow this suggestion:
```On the candidates tab, there's a button labeled "Import from CVR sources" that triggers an immediate parsing of the source files, then overwrites the displayed list with whatever it finds. (In other words, the candidates still go in the config file, but we help the user auto-populate them.)```

This will be implemented one CVR source at a time, and will likely not include all sources for the first version. I'll create additional tasks for each version not implemented.

I will not deal with aliases -- all candidate names found will be listed as their own candidate. The user can delete a candidate and add that name as an alias of another candidate if needed. If this becomes cumbersome, we can create a task to make this simpler, e.g. click and drag one candidate onto another to make it an alias. I suspect that's an edge case that we won't need to make super user-friendly for V1.


In sum, the plan:
1. A button that looks through a CVR and guesses at the candidate names
2. A preview that lists all found candidate names. User can hit OK or Cancel.
3. For each candidate name encountered not yet entered, it adds them to the list
4. Will start with the easiest CVR type first, create a pull request, and after it's merged, add additional CVR types. This is to keep the first PR small.

**Comment by HEdingfield** [comment]
No idea why this issue auto-closed.
