### ISSUE TITLE
NPE due to missing `GpUnit` when parsing XML CDF

### ISSUE THREAD

**Issue by HEdingfield** [BrightSpots/rcv#624]
I used the config file and CDF XML input provided by @rrojas350 via email on 2023-01-09 and can confirm that I get an NPE when attempting to tabulate:

> 2023-01-21 22:42:31 PST INFO: Reading CDF cast vote record file: C:\...\OVOUVS019011-1672852461_cvr_1_of_1.xml...
> 2023-01-21 22:47:23 PST SEVERE: Unexpected error parsing source file: C:\...\OVOUVS019011-1672852461_cvr_1_of_1.xml
> java.lang.NullPointerException: Cannot read the array length because "< local9 >" is null

(But remove the spaces from `< local9 >` because it's apparently some kind of special tag that GH won't display.)

Using the IntelliJ debugger, it seems this triggers around line 170 in `CommonDataFormatReader.java`:

`for (GpUnit gpUnit : cvrReport.GpUnit) {`

Because `cvrReport.GpUnit` is `null`. If I surround this logic with a simple `if (cvrReport.GpUnit != null) {`, the NPE doesn't happen, but it results in "No cast vote records found!".

It appears that `GpUnit` isn't being read properly for this particular file.

**Comment by tarheel** [comment]
That's happening because GpUnit is missing entirely from the source file.

This source file just generally doesn't seem to be consistent with the Common Data Format that our code is expecting. Other problems I found:
- The CurrentSnapshotId field is missing from every CVR.
- Some Candidate elements are duplicated.
- The ContestSelection elements under each Contest are wrong. Each Contest only has one ContestSelection with no child nodes (and an ID that matches the Contest's ID). But our code is expecting each Contest to contain a list of ContestSelections, where each of those ContestSelections contains a CandidateIds elem ents that contains one of the valid candidates for that contest.

**Comment by tarheel** [comment]
Example of valid Unisyn CDF XML: https://github.com/BrightSpots/rcv/blob/develop/src/test/resources/network/brightspots/rcv/test_data/unisyn_cvrs/797-GEN-OVCS_Sess_3_Combined_UVSOVS22516.xml

**Comment by HEdingfield** [comment]
Sounds like it's a data quality issue, but it might still be nice to at least add some guard clauses that give friendlier error messages if any of these expected keys are missing.

**Comment by rrojas350** [comment]
Any thoughts on messaging such as "CDF CVR Read Error" or "Unexpected CVR"? It would be nice to have some better messaging around this type of error to help us narrow down the issue when trouble shooting.

**Comment by tarheel** [comment]
For sure. We can probably have the app cite the specific required element (e.g. GpUnit) that's missing from the CVR.

**Comment by artoonie** [comment]
Can you upload the XML file?

**Comment by rrojas350** [comment]
Sure thing @artoonie. Here you go: 

[Issue 624 XML and Config](https://drive.google.com/drive/folders/1oe0ixRxmb94NeL8sIa0_dsGUTx1XQuU7?usp=sharing)

The issue with this XML was that this CVR was an older version of Unisyn's CDF CVR, which is not compatible with RCTab.
