### ISSUE TITLE
Block using newer config with older version of RCTab

### ISSUE THREAD

**Issue by HEdingfield** [BrightSpots/rcv#712]
As discussed in https://github.com/BrightSpots/rcv/pull/701#discussion_r1234446275, attempting to use the tabulator with a newer config file version should throw an exception and halt it.

Attempting to run an older config with a newer version of the tabulator should attempt migration (possibly related to / to be handled in https://github.com/BrightSpots/rcv/issues/706).

We should make sure this WAI with the CLI commands as well.

**Comment by artoonie** [comment]
It turns out tabulation IS blocked, both in GUI and CLI, but not where I expected--

the function `checkConfigVersionMatchesApp` just logs a SEVERE message, but it seems like that message can never get logged: the migration checks for mismatched version numbers, and migration always runs first. This makes `checkConfigVersionMatchesApp` a no-op as-is, best I can tell.

I think there are two reasonable options:
1. Get rid of `checkConfigVersionMatchesApp` entirely
2. Leave it in as a safety net, and as such, throw an exception instead of just logging


I opted for (2) in this PR, but can see an argument for either option.

**Comment by HEdingfield** [comment]
Looked into this more and mostly think we should actually leave this as-is, as it seems to just be some extra, helpful logging for CLI users.
