### ISSUE TITLE
better error detection for malformed source files

### ISSUE THREAD

**Issue by tarheel** [BrightSpots/rcv#83]
If a source file exists but has issues, the code doesn't handle it gracefully.

Things to check:
- invalid file type (renamed to .xlsx) (see #267)
- missing columns
- missing IDs or precincts
- unexpected cell type (see #180)  firstVoteColumnIndex was mistakenly pointing at the column with the ballot IDs,
- other?

**Comment by CalebKleppner** [comment]
This should be taken care of when our validate config file routine starts working in v 0.8 GUI, so I put this on milestone v 0.9 to make sure we've covered all the bases by then.

**Comment by moldover** [comment]
@gngilbert @CalebKleppner  I'm putting in some stricter checks around CVR file parsing to help users identify problems with CVR files.  If a user specifies precinct ID column, should we fail the tabulation if we encounter ballots which don't have a precinct ID?

**Comment by CalebKleppner** [comment]
I'd say that we should not stop the tabulation, since we sometimes get 
an odd file or two lacking a precinct identifier.  What would happen to 
precinct report if you have records with no precinct identifier?  If 
they can all be collected in [null] or [precinct ID missing], that would 
be ideal.

Caleb Kleppner
MK Election Services, LLC
203-376-4080

**Comment by CalebKleppner** [comment]
I'd say that we should not stop the tabulation, since we sometimes get 
an odd file or two lacking a precinct identifier.  What would happen to 
precinct report if you have records with no precinct identifier?  If 
they can all be collected in [null] or [precinct ID missing], that would 
be ideal.

Caleb Kleppner
MK Election Services, LLC
203-376-4080

On 6/24/2019 12:53 PM, Jon Moldover wrote:

Caleb Kleppner
203-376-4080

**Comment by moldover** [comment]
Sure, that should be easy enough.

**Comment by moldover** [comment]
Closed #314
