### ISSUE TITLE
Columns specified in config file shouldn't be 0-indexed

### ISSUE THREAD

**Issue by HEdingfield** [BrightSpots/rcv#84]
This has proven to cause off-by-one errors / confusion with our users.

1. Proposed short-term fix: change all column references in config file to be 1-indexed.
2. Proposed long-term fix: UI should scrape column labels and present them in a dropdown for users to choose from.

**Comment by CalebKleppner** [comment]
Agreed.  ColumnIndex=1 really should be the first column, not the second column.  Ideally you have a ballotID field in the CVR, which is helpful for auditing, but, for example, the Minneapolis data doesn't have that, so it's good that we assign a ballot ID to each CVR.  Problem is that it's not always easy to link our ballot ID back to the actual record in the CVR.  

Possible fix is to have another ColumnIndex, BallotIDColumnIndex, which would be an optional parameter, and if it exists, we pull the BallotID from the CVR.  I think it's still a good idea for the tabulator to create a unique ballot ID for every CVR read, in part because CVRs may not have unique BallotIDs (dupes are possible) and it's nice to have a unique ID for every record.

**Comment by tarheel** [comment]
Yes, we have an optional idColumnIndex param for reading the ballot ID from the CVR row. We also generate our own unique ID for each ballot.

**Comment by HEdingfield** [comment]
Maybe the proposed long-term fix is worth filing as a separate issue beyond 1.0? Not sure.

**Comment by tarheel** [comment]
#167
