### ISSUE TITLE
Logger hanging in Windows when 'Open Log' button fails

### ISSUE THREAD

**Issue by yezr** [BrightSpots/rcv#840]
> In my test run (both with `2013_minneapolis_park_config.json` and `dominion_alaska_config.json`), this button didn't work and I got a warning in the logs saying:

> WARNING: Failed to open file explorer: Cannot run program "open": CreateProcess error=2, The system cannot find the file specified

Then window then stayed open and I had to X out of it to get rid of it.

The file definitely exists... I'm guessing this has to do with Windows maybe behaving differently than a Mac? I'm on Windows 11.

Another issue arising from this: I noticed that no message appeared in the logger window the first couple times I clicked, and then the third time it appeared with three messages.

_Originally posted by @HEdingfield in https://github.com/BrightSpots/rcv/pull/812#discussion_r1625226102_

**Comment by artoonie** [comment]
I believe the first issue (opening logger in Explorer) is fixed, and the only remaining issue is the last bit (no messages appear, then all appear at once).

@HEdingfield can you let us know if you continue to encounter that issue? I'm testing on Windows and haven't seen it happen yet.

**Comment by HEdingfield** [comment]
Correct, just the second point needs addressing now. And yes, I can still repro it by making it so this line:

`Logger.warning("Failed to open file explorer: " + e.getMessage());`

Gets triggered whenever the button is clicked (via `throw new IOException();` above it), then clicking the button a number of times. The first few times will often work, but if I click it 4 or 5 times, it'll only show 3 or 4 messages below, until I click it some more and then a number of extra catch-up messages will show.

As mentioned in the comment, I suspect it's due to the code around the comment you wrote in `Logger.java` saying:

`// we add to a queue and schedule an occasional update to the UI.`
