### ISSUE TITLE
Percentages in summary .csv file always add up to less than 100%

### ISSUE THREAD

**Issue by chughes297** [BrightSpots/rcv#868]
See attached. I assume this is because we truncate all percentage values at the 4th decimal place? I found this [stack overflow post](https://stackoverflow.com/questions/13483430/how-to-make-rounded-percentages-add-up-to-100) that appears to have a few different possible solutions to this. 

FWIW I'm glad we're winding up with less than 100% and not more than 100%. 

[2024-06-12_14-23-47_summary.csv](https://github.com/user-attachments/files/16087642/2024-06-12_14-23-47_summary.csv)

**Comment by artoonie** [comment]
Yes, and this is pretty common -- I'm not sure we want any of the "fixes," since they all "fix" the issue by creating incorrect percentages. We can either have the numbers add up to 100 exactly, or we can have the percentages be exactly correct, but not both.

The phrase "Percentages may not add up to 100 because of rounding." is common: https://www.google.com/search?hl=en&q=%22Percentages%20may%20not%20add%20up%20to%20100%20because%20of%20rounding.%22

[e.g. this article on the NYT](https://www.nytimes.com/interactive/2022/07/11/opinion/immigrants-success-america.html)

**Comment by yezr** [comment]
added `needs-rcvrc-clarification` tag. Will review at next bi-weekly review (aka the RCTab Download™) on July 9 and update here after

**Comment by yezr** [comment]
After discussion we're going to leave this as is. No amount of showing more decimal places will get us to exactly 100%, and any method to match 100% could show a candidate with more or less support than they actually have. For the extremely determined observer who wants to know **exactly** what percentage a candidate has they have the vote tallies to do that in the next column over.
