### ISSUE TITLE
rcv.log silently becomes huge

### ISSUE THREAD

**Issue by HEdingfield** [BrightSpots/rcv#93]
Realized I had a 200 MB (and growing) rcv.log file sitting in the main directory. Can we address this somehow? Maybe at least break them up into a separate "logs" folder with filenames like rcv_X.log where X is tabulator start date and time? How do other programs handle ever-expanding log files?

**Comment by tarheel** [comment]
Typically you would expect the system to have some process for keeping it under control. I like the idea of separating the output by timestamp. We could also make the app automatically find and erase any logs that are older than X days.

**Comment by moldover** [comment]
Yep, the logging utility has built-in features for rolling over or splitting logs based on time or size.  I prefer a size split (or daily) because it facilitates debugging across application runs (e.g. batch execution, or a user can't remember exactly when something glitched...)

**Comment by CalebKleppner** [comment]
It looks to me like rcv.log is a file that contains an ever-growing log of every tabulation that is run.  I've deleted it a few times when it got too big.  Depending on how we format our logging output, that log can get pretty big, so I'd favor tagging the logfile with tabulation start date and time (rcv_2018-07-25_11-40-19.log), since even a single tabulation might exceed whatever cap size we choose.  Am I correct that the entries in rcv.log are duplicates of the entries in the  audit.log file?  So the main purposes is the simultaneous logging of events in cases where the audit.log file doesn't get created?  If so, we might save some time and performance by eliminating one copy.

**Comment by moldover** [comment]
@CalebKleppner the main point of a separate "rcv.log" is for capturing actions which are outside a tabulation run, for example launching the gui, editing config files, etc.  This is helpful for internal debugging and perhaps record-keeping for running batch executions and unit tests, but on reflection I don't think rcv.log should be part of "official" tabulation outputs nor should we spend much time massaging it's output.  Certainly we should not be duplicating the _audit_ logging in the rcv.log file since that is redundant.  Fixing this will greatly reduce the rcv.log file size, and combined with a reasonable rollover strategy, should (I hope) mean we don't have to worry about this anymore.

**Comment by HEdingfield** [comment]
Agreed, this sounds good to me. Let's keep this issue open a little while after making this change though to get a sense of how big it gets (since we may want to create some overflow option if it's still necessary... hopefully it won't be though).

**Comment by moldover** [comment]
Thinking still further, what about splitting the execution and tabulation log outputs entirely (no duplication).  Something like this:

Execution log:  gui actions, config validation errors, ...
log to file: current/working/dir/rcv.log
log to console: yes
log to GUI: yes
example: "loaded my_config.json"  "validate my_config.json failed: no candidates specified"
storage policy: rollover: 2 files, 50MB max

Tabulation log: tabulation runs, cvr + config file inputs, hashes, round by round summary, audit
log to file: config/output/folder/location/<timestamp_when_execution_starts>_audit.log
log to console: yes but could skip this for speed if we want
log to GUI: yes, but not the audit

**Comment by tarheel** [comment]
This sounds good. Big +1 to not duplicating all the tabulation output in rcv.log.
